---
title: "PEC2 - Estudio de técnicas de visualización de datos"
author: "Martín Leal Martínez"
date: "4/20/2022"
output: html_document
---
```{r, echo=FALSE, results='hide', message=FALSE, warning=FALSE}
# setup
library(tidyverse)
library(vistime)
```
### TIMELINE

```{r, echo = FALSE}
# Creamos el conjunto de datos
data <- read.csv(text="event,group,start,end,color
                       Etapa 1,Etapas,1939-01-01,1941-12-31,#DEEBF7
                       Etapa 2,Etapas,1942-01-01,1943-12-31,#C6DBEF
                       Etapa 3,Etapas,1944-01-01,1945-12-31,#9ECAE1
                        ,Alemania invade Polonia,1939-09-01,1939-09-01, #DEEBF7
                        ,Francia e Inglaterra declaran la guerra a Alemania,1939-09-03, 1939-09-03,#DEEBF7
                        ,Alemania toma París, 1940-06-22, 1940-06-22, #DEEBF7
                        ,Alemania invade la Unión Soviética, 1941-06-22, 1941-06-22, #DEEBF7
                        ,Japón bombardea la base Pearl Harbor, 1941-12-07, 1941-12-07, #DEEBF7
                        ,Inglaterra derrota Alemania en África, 1942-11-03, 1942-11-03, #C6DBEF
                        ,Alemania es derrotada en Stalingrado, 1943-02-02, 1943-02-02, #C6DBEF
                        ,Los aliados invaden Italia, 1943-09-03, 1943-09-03, #C6DBEF
                        ,Día D. Desembarco de Normandía, 1944-06-06, 1944-06-06, #9ECAE1
                        ,Alemania es derrotada en la batalla de Normandía, 1944-08-25, 1944-08-25, #9ECAE1
                        ,Adolf Hitler se suicida en Berlín, 1945-04-30, 1945-04-30, #9ECAE1
                        ,EE.UU. lanza una bomba nuclear en Hiroshima, 1945-08-06, 1945-08-06, #9ECAE1")

# Representamos la línea temporal
vistime(data, linewidth = 25, title = "Principales acontecimientos de la Segunda Guerra Mundial")
```



### BOXPLOT

```{r, echo=FALSE}
# Utilizamos el conjunto mpg de R que contiene información acerca de distintos modelos de coches
# Realizamos un boxplot a partir del consumo en autopista de las diferentes marcas
ggplot(mpg, mapping = aes(x = manufacturer, y = hwy)) +
  geom_boxplot() + 
  coord_flip() +
  labs(y = "\nConsumo en autopista (L/100 km)",
       x = "Fabricante\n",
       title = "Distribución del consumo de combustible de los principales fabricantes.\n")
```

### CONNECTED SCATTERPLOT

```{r, echo=FALSE}
#these libraries need to be loaded
library(utils)

#read the Dataset sheet into “R”. The dataset will be called "data".
data <- read.csv("https://opendata.ecdc.europa.eu/covid19/nationalcasedeath_eueea_daily_ei/csv", na.strings = "", fileEncoding = "UTF-8-BOM")
```


```{r, echo=FALSE}
# Limpiamos el conjunto de datos
data = data %>%
  filter(deaths >= 0) %>%
  group_by(dateRep) %>% 
  summarise(deaths = sum(deaths)) %>%
  mutate(dateRep = as.Date(dateRep, "%d/%m/%Y")) %>%
  arrange(dateRep)
```

```{r, echo=FALSE}
# Creamos la visualización

ggplot(data, aes(x = dateRep, y = deaths)) +
  geom_path() +
  labs(x = "\nFecha", y = "Fallecidos\n",
 title ="Evolución del número de fallecidos por COVID - 19.\n")
```

